name: CMake Build (Ubuntu)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache CMake build
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-build-${{ hashFiles('CMakeLists.txt') }}

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.25.0'

      - name: Install raylib dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            xorg-dev \
            libglu1-mesa-dev \
            libgl1-mesa-dev \
            libxcursor-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxi-dev \
            libx11-dev \
            libasound2-dev \
            libpulse-dev \
            libopenal-dev

      - name: Configure project
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --config Release -- -j 4 --verbose

      - name: List build outputs
        run: ls -R build/bin

      - name: Upload built binary
        uses: actions/upload-artifact@v4
        with:
          name: zentype-linux
          path: build/bin/
