name: CMake CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.25.0'

      # Linux dependencies for raylib
      - name: Install raylib dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            xorg-dev \
            libglu1-mesa-dev \
            libgl1-mesa-dev \
            libxcursor-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxi-dev \
            libx11-dev \
            libasound2-dev \
            libpulse-dev \
            libopenal-dev

      - name: Configure project
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --config Release -- -j 4

      - name: List build outputs
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            dir build\\bin
          else
            ls -R build/bin
          fi

      # Optional: Upload binaries so you can download them from GitHub Actions
      - name: Upload built binaries
        uses: actions/upload-artifact@v4
        with:
          name: zentype-${{ matrix.os }}
          path: build/bin/
